---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server-stateful-set
  labels:
    app: server
spec:
  serviceName: "server-service"
  replicas: 4
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: eu.gcr.io/ne-leila-rc1t/server:1.4.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: server-config
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: pv-claim
              mountPath: /data
        - name: logger
          image: eu.gcr.io/ne-leila-rc1t/logger:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - name: pv-claim
              mountPath: /data
      serviceAccountName: server-service-account
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - server
              topologyKey: "kubernetes.io/hostname"
  volumeClaimTemplates:
    - metadata:
        name: pv-claim
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
