---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server-stateful-set
  labels:
    app: server
spec:
  serviceName: "server-service"
  replicas: 4
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: eu.gcr.io/ne-leila-rc1t/server:1.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: server-config
          volumeMounts:
            - name: server-volume
              mountPath: /data
        - name: logger
          image: eu.gcr.io/ne-leila-rc1t/logger:1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - name: server-volume
              mountPath: /data
      volumes:
        - name: server-volume
          persistentVolumeClaim:
            claimName: pv-claim
