apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: eu.gcr.io/ne-leila-rc1t/server:1.1.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: server-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
data:
  LOCATION: sweden
  USER: leila